# Generated by Django 5.1 on 2024-11-14 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('societyapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='description',
            new_name='content',
        ),
    ]
